exports.deliveryLocators = {
  headerText: 'div.nopurge_headline_1OkWXZV- > h2',
  selectCityField: 'div.nopurge_textContainer_2erQ05GV',
  selectCity: 'div:nth-child(1) > div > div.nopurge_options_FvXJIKt0',
  flatNo: 'input[name="number"]',
  buildingName: 'input[name="buildingName"]',
  streetName: 'input[name="streetName"]',
  developmentName: 'input[name="developmentName"]',
  area: 'input[name="area"]',
  phoneNo: 'input[name="alternatePhone"]',
  billingHeader: 'div.nopurge_switcherTitle_1w7V49U2',
  billingDetailsToggleText: 'div.nopurge_note_2OeE37Uo',
  billingDetailsToggle: 'label > div',
  continueBtn: 'div#__layout form > button',
  orderSummary: {
    headerText: 'div.nopurge_headline_2SXmUBbl > h2',
    recipePerWeek: 'div.nopurge_infoRow_25hLB1o8 > div.nopurge_info_3brZnr1t',
    totalServings: 'div.nopurge_infoRow_25hLB1o8 > div.nopurge_value_1Qhbk-KP',
    boxPrice: 'div:nth-child(1) > div.nopurge_info_3brZnr1t',
    boxPriceValue: 'div:nth-child(1) > div.nopurge_value_1Qhbk-KP',
    deliveryFee: 'div.nopurge_priceContainer_3lSxQlAt > div:nth-child(2) > div.nopurge_info_3brZnr1t',
    deliveryFeeText: 'div.nopurge_priceContainer_3lSxQlAt > div:nth-child(2) > div.nopurge_value_1Qhbk-KP',
    vat: 'div:nth-child(3) > div.nopurge_info_3brZnr1t',
    vatValue: 'div:nth-child(3) > div.nopurge_value_1Qhbk-KP',
    grandTotal: 'div:nth-child(4) > div.nopurge_info_3brZnr1t',
    grandTotalValue: 'div:nth-child(4) > div.nopurge_value_1Qhbk-KP',
  },
  deliverySummary: {
    headerText: 'div:nth-child(2) > div:nth-child(1) > h2',
    deliveryInstructions: 'div.nopurge_headingRow_1beOJSEn > div',
    editButton: 'div.nopurge_headingRow_1beOJSEn > button',
    firstDelivery: 'div.nopurge_informationSubtitle_2NMlLEyk',
    deliveryDay: 'div.nopurge_deliveryInformation_2OKenfek > div:nth-child(2)',
    deliveryTime: 'div.nopurge_info_xA7eKeEs.nopurge_time_1PWAOlWK',
  },
  editDelivery: {
    doneBtn: 'div.nopurge_headingRow_1beOJSEn > button', // check for color to be green
    deliveryDateDropDownHeader: 'div.nopurge_deliveryInformation_2OKenfek > div:nth-child(1) > span',
    deliveryDateDropDownSelector: 'div.nopurge_deliveryInformation_2OKenfek > div:nth-child(1) > div > div',
    deliverDateValue: 'span[aria-disabled="false"].vc-day-content',
    // need to write selectors for date, will resume when internet is working
    deliveryTimeDropDownHeader: 'div.nopurge_deliveryInformation_2OKenfek > div:nth-child(2) > span',
    deliveryTimeDropDownParent: 'div.nopurge_right_vyY8g-0S div.nopurge_options_FvXJIKt0',
    deliveryTimeDropDownSelector: 'div.nopurge_deliveryInformation_2OKenfek > div:nth-child(2) > div',
    deliveryTimeDropDownValue: 'div.nopurge_right_vyY8g-0S div.nopurge_options_FvXJIKt0 > div:nth-child(?)',
    otherNotes: 'div.nopurge_deliveryInformation_2OKenfek > label > span',
    otherNotesTextArea: 'div#__layout textarea',
  },
  calendar: {
    calendarCloseBtn: 'div.nopurge_visible_1Tp97K4F .nopurge_iconBorder_36CfnA1s',
  },
};
