exports.footer = {
  desktop: {
    logo: '.self-center .desktop\\:h-32',
    aboutUsBox: '.desktop\\:mt-28 :nth-child(2)',
    moreInfoBox: '.mobile\\:text-right',
    ourBlogBox: '.col-4',
    contactUsBox: '.col-8',
    subscribeToNL: 'form.col-12',
    reviews: '.desktop\\:mt-34 .desktop\\:col-4',
    socialMediaHandles: '.desktop\\:col-3.text-center',
    madeInUAE: '.desktop\\:mt-24',
    chatIcon: '.intercom-lightweight-app-launcher-icon-open',
  },

  mobile: {
    logo: '.nopurge_footerMobile_2EAxFmkS #__9gAI8i4__horizontal-bell-pepper-red',
    aboutUs: 'div.nopurge_container_1IQ6l7NY.nopurge_footerMobile_2EAxFmkS > div:nth-child(2) > div > div:nth-child(1) > div',
    ourBoxes: 'div.nopurge_footerMobile_2EAxFmkS  a[href="/our-boxes"',
    howItWorks: 'div.nopurge_footerMobile_2EAxFmkS  a[href="/how-it-works"',
    moreInfo: 'div.nopurge_moreInfoContainer_3ClgW9vJ > div',
    sustainability: 'div.nopurge_moreInfoContainer_3ClgW9vJ a[href="/recycle"]',
    faq: 'div.nopurge_moreInfoContainer_3ClgW9vJ a[href="/faq"]',
    blog: 'div.nopurge_moreInfoContainer_3ClgW9vJ a[href="https://blog.hellochef.me"]',
    contactUs: 'div.nopurge_container_1IQ6l7NY.nopurge_footerMobile_2EAxFmkS > div:nth-child(3) > div',
    mailTo: 'div.nopurge_section_3YO5YbQ4 a[href="mailto:hello@hellochef.me"]',
    phoneNumber: 'div.nopurge_section_3YO5YbQ4 a[href="tel:043839399"]',
    subscribeToNL: 'div.nopurge_container_1IQ6l7NY.nopurge_footerMobile_2EAxFmkS > div:nth-child(4) > div',
    enterYourEmail: 'div:nth-child(4) > form > label .nopurge_inputTitle_huiNZv4J',
    subscribeBtn: 'div:nth-child(4) > form > label button',
    inputEmail: 'div:nth-child(4) input[name="email"]',
    followUs: 'div:nth-child(5) > div.nopurge_title_3Od6sfNQ',
    socialIcons: 'div:nth-child(5) > div.nopurge_socialRows_3Sx37-OW',
    fbIcon: 'div:nth-child(5) > div.nopurge_socialRows_3Sx37-OW span[alt="Facebook"]',
    instagramIcon: 'div:nth-child(5) > div.nopurge_socialRows_3Sx37-OW span[alt="Instagram"]',
    youtubeIcon: 'div:nth-child(5) > div.nopurge_socialRows_3Sx37-OW span[alt="YouTube"]',
    // tiktokIcon : 'div:nth-child(5) > div.nopurge_socialRows_3Sx37-OW span[alt="TikTok"]'
    madeInUAE: 'div.nopurge_additionalTitle_1HiXT5vZ',
    copyRight: 'div.nopurge_note_3WI3aiAL',
  },
};
