exports.paymentDetails = {
  headerText: 'div#__layout h1',
  cardNumberIframe: '#cardNumber',
  cardNumberField: '#checkout-frames-card-number',
  cardExpiryIframe: '#expiryDate',
  cardExpiryDate: '#checkout-frames-expiry-date',
  cardCVVIframe: '#cvv',
  cardCVV: '#checkout-frames-cvv',
  checkoutIframe: 'iframe[name="cko-3ds2-iframe"]',
  checkoutPageContinueBtn: '#txtButton',
  promoCode: 'input[name="promocode"]',
  applyPromoBtn: 'button.nopurge__theme_inverted_3oqvLE5u',
  orderSummary: {
    headerText: '.nopurge_headline_2SXmUBbl h2',
    recipeAndServingSummary: '.nopurge_innerContent_uq_CD9wG .nopurge_infoRow_25hLB1o8',
    // iterate ? from 1 to 4
    priceKey: '.nopurge_priceContainer_3lSxQlAt > div:nth-child(?) .nopurge_info_3brZnr1t',
    priceValue: '.nopurge_priceContainer_3lSxQlAt > div:nth-child(?) .nopurge_value_1Qhbk-KP',
  },
  deliveryDetails: {
    headerText: '.nopurge_deliverySummary_QcU6JlJH h2',
    deliveryInstructions: '.nopurge_deliverySummary_QcU6JlJH .nopurge_subtitle_3fNIygrH',
    editInstructionsBtn: '.nopurge_deliverySummary_QcU6JlJH .nopurge__theme_white_3j2gvLln',
    firstDeliveryKey: '.nopurge_deliverySummary_QcU6JlJH .nopurge_informationSubtitle_2NMlLEyk',
    firstDeliveryValue: '.nopurge_deliverySummary_QcU6JlJH .nopurge_info_xA7eKeEs',
    deliveryTime: '.nopurge_deliverySummary_QcU6JlJH .nopurge_info_xA7eKeEs.nopurge_time_1PWAOlWK',
    deliveryAddressKey: '.nopurge_deliveryInfo_2-SfacqF .nopurge_title_3XueGree',
    editDeliveryaddress: '.nopurge_deliveryInfo_2-SfacqF .nopurge_withIcon_1QOTuw2B',
    deliveryAddressValue: '.nopurge_deliveryInfo_2-SfacqF > div:nth-child(2)',
  },
  saveMoneyText: '.nopurge_right_vyY8g-0S .nopurge_subtitle_1wYHJoQx',
  paynowBtn: '.nopurge_right_vyY8g-0S .nopurge_btn_1lj1LrF9',
  finePrint: '.nopurge_right_vyY8g-0S .nopurge_note_23qpP93b',
  checkoutPassword: 'input#password',
  paynowBtnWeb: 'div#__layout div.nopurge_controlsDesktop_nwrll43R > div > button',
};
